// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Parcial2_Aplicada1_2017_0485.DAL;

namespace Parcial2_Aplicada1_2017_0485.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20210309021559_Proyectos")]
    partial class Proyectos
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("Parcial2_Aplicada1_2017_0485.Entidad.Proyectos", b =>
                {
                    b.Property<int>("ProyectoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<int>("Tiempo")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProyectoId");

                    b.ToTable("Proyectos");
                });

            modelBuilder.Entity("Parcial2_Aplicada1_2017_0485.Entidad.Proyectos_Detalles", b =>
                {
                    b.Property<int>("ProyectoDetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProyectoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Requerimiento")
                        .HasColumnType("TEXT");

                    b.Property<int>("TareaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tiempo")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProyectoDetalleId");

                    b.HasIndex("ProyectoId");

                    b.HasIndex("TareaId");

                    b.ToTable("Proyectos_Detalles");
                });

            modelBuilder.Entity("Parcial2_Aplicada1_2017_0485.Entidad.Tareas", b =>
                {
                    b.Property<int>("TareaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.HasKey("TareaId");

                    b.ToTable("Tareas");

                    b.HasData(
                        new
                        {
                            TareaId = 1,
                            Descripcion = "Analisis"
                        },
                        new
                        {
                            TareaId = 2,
                            Descripcion = "Diseño"
                        },
                        new
                        {
                            TareaId = 3,
                            Descripcion = "Programacion aplicada"
                        });
                });

            modelBuilder.Entity("Parcial2_Aplicada1_2017_0485.Entidad.Proyectos_Detalles", b =>
                {
                    b.HasOne("Parcial2_Aplicada1_2017_0485.Entidad.Proyectos", null)
                        .WithMany("Detalles")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parcial2_Aplicada1_2017_0485.Entidad.Tareas", "tarea")
                        .WithMany()
                        .HasForeignKey("TareaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tarea");
                });

            modelBuilder.Entity("Parcial2_Aplicada1_2017_0485.Entidad.Proyectos", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
